### ISSUE TITLE
Generalise the enemy class.

### ISSUE THREAD

**Issue by WSeegers** [TalPat/Bomberman#41]
Create a interface on the enemy class to allow for the creation of enemies.

Create a second enemy type and include an array of IEnemy to the game state.

**Comment by agabrie** [comment]
I created a List in the gameState, not certain if thats what was expected

**Comment by WSeegers** [comment]
The list will have to be changed to accept IEnemy pointers.

**Comment by agabrie** [comment]
Can I close
